name: Codecov 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: prepare build dir
      run: mkdir -p build/
    - name: cmake
      run: cmake .. -Dcoverage=ON
      working-directory: build/
    - name: make
      run: make test_all
      working-directory: build/
    - name: run tests
      run: ./test/test_all
      working-directory: build/
    - uses: codecov/codecov-action@v1
